spring.application.name=auction
spring.datasource.url=jdbc:postgresql://100.89.153.39:5432/auctiondb
spring.datasource.username=postgres
spring.datasource.password=getapass
server.port = 8080
# spring.jackson.property-naming-strategy=LOWER_CASE