spring.application.name=auction
server.address=0.0.0.0
server.port=8080
# --- SQLite Database Configuration ---
# Creates a file named auctiondb.db in your project root folder
spring.datasource.url=jdbc:sqlite:auctiondb.db
spring.datasource.driver-class-name=org.sqlite.JDBC
# Tell Hibernate to use the SQLite community dialect
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
# Automatically update your database schema when you change your entity classes
spring.jpa.hibernate.ddl-auto=update
# --- Old PostgreSQL settings ---
# spring.datasource.url=jdbc:postgresql://100.89.153.39:5432/auctiondb
# spring.datasource.username=postgres
# spring.datasource.password=getapass
# --- JWT Configuration ---
jwt.secret=${JWT_SECRET:245cd2618f11d11d206e3131ee119341eb6f6926a35acefbcbfe1f05fb50fb20}
# these are in miliseconds

# 6 minutes (360,000ms)
jwt.expiration=360000

#7 days.
jwt.refreshExpiration=604800000

# Two hours (7,200,000ms)
max_extra_time=7200000
# 6 minutes (360,000ms)
extra_time=360000

spring.datasource.hikari.maximum-pool-size=1

# ban hash
ban_hash = 1

logging.level.root=WARN
logging.level.com.auction=INFO