spring.application.name=auction
spring.datasource.url=jdbc:postgresql://100.89.153.39:5432/auctiondb
spring.datasource.username=postgres
spring.datasource.password=getapass
server.port = 8080
# spring.jackson.property-naming-strategy=LOWER_CASE
jwt.secret = 245cd2618f11d11d206e3131ee119341eb6f6926a35acefbcbfe1f05fb50fb20
jwt.expiration = 360000